//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MezbanData.DbContext
{
    using System;
    using System.Collections.Generic;
    
    public partial class EmailTemplate
    {
        public int Id { get; set; }
        public string MailFrom { get; set; }
        public string MailTo { get; set; }
        public string CC { get; set; }
        public string Subject { get; set; }
        public string Code { get; set; }
        public Nullable<bool> Status { get; set; }
        public string Title { get; set; }
        public string Content { get; set; }
    }
}
