//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MezbanData.DbContext
{
    using System;
    using System.Collections.Generic;
    
    public partial class Menu
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Menu()
        {
            this.MenuItems = new HashSet<MenuItem>();
        }
    
        public System.Guid MenuId { get; set; }
        public long ContentdefinitionId { get; set; }
        public Nullable<decimal> Price { get; set; }
        public System.Guid RestaurantId { get; set; }
        public string Code { get; set; }
        public Nullable<bool> Status { get; set; }
        public Nullable<int> SortOrder { get; set; }
        public Nullable<decimal> Rate { get; set; }
        public string Name { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public string CreatedBy { get; set; }
        public System.DateTime ModifiedDate { get; set; }
        public string ModifiedBy { get; set; }
        public long SeqId { get; set; }
    
        public virtual Contentdefinition Contentdefinition { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MenuItem> MenuItems { get; set; }
        public virtual Restaurant Restaurant { get; set; }
    }
}
