//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MezbanData.DbContext
{
    using System;
    using System.Collections.Generic;
    
    public partial class Option
    {
        public System.Guid OptionId { get; set; }
        public long ContendifinitonId { get; set; }
        public string Code { get; set; }
        public System.Guid MenuItemId { get; set; }
        public Nullable<decimal> Price { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public string CreatedBy { get; set; }
        public System.DateTime ModifiedDate { get; set; }
        public string ModifiedBy { get; set; }
    
        public virtual Contentdefinition Contentdefinition { get; set; }
        public virtual MenuItem MenuItem { get; set; }
    }
}
