//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MezbanData.DbContext
{
    using System;
    using System.Collections.Generic;
    
    public partial class Order
    {
        public System.Guid OderId { get; set; }
        public System.Guid RestaurantId { get; set; }
        public string RestaurantName { get; set; }
        public string UserId { get; set; }
        public System.DateTime OderDate { get; set; }
        public Nullable<decimal> TotalPrice { get; set; }
        public Nullable<int> Status { get; set; }
        public Nullable<decimal> TaxTotal { get; set; }
        public string OderReq { get; set; }
        public string CheckSum { get; set; }
        public string OrderCode { get; set; }
        public Nullable<decimal> PaymentWith { get; set; }
        public Nullable<int> DiscountPercent { get; set; }
        public string ReasonReject { get; set; }
        public string ReasonCancel { get; set; }
        public Nullable<decimal> ChargeFee { get; set; }
        public Nullable<decimal> DeliveryCost { get; set; }
    
        public virtual AspNetUser AspNetUser { get; set; }
        public virtual Restaurant Restaurant { get; set; }
    }
}
