//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MezbanData.DbContext
{
    using System;
    using System.Collections.Generic;
    
    public partial class PromotionLineItem
    {
        public long PromotionLineItemId { get; set; }
        public System.Guid PromotionId { get; set; }
        public System.Guid RestauranId { get; set; }
        public string Code { get; set; }
        public string Name { get; set; }
    
        public virtual Promotion Promotion { get; set; }
        public virtual Restaurant Restaurant { get; set; }
    }
}
