//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MezbanData.DbContext
{
    using System;
    using System.Collections.Generic;
    
    public partial class RestaurantWorkTime
    {
        public long RestaurantWorkTimeId { get; set; }
        public System.Guid RestaurantId { get; set; }
        public string CloseTime { get; set; }
        public string OpenTime { get; set; }
        public string WeekDay { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public string CreatedBy { get; set; }
        public System.DateTime ModifiedDate { get; set; }
        public string ModifiedBy { get; set; }
    
        public virtual Restaurant Restaurant { get; set; }
    }
}
