//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MezbanData.DbContext
{
    using System;
    using System.Collections.Generic;
    
    public partial class RestaurantCategory
    {
        public long RestaurantCategoryId { get; set; }
        public System.Guid RestaurantId { get; set; }
        public System.Guid CategoryId { get; set; }
    
        public virtual Category Category { get; set; }
        public virtual Restaurant Restaurant { get; set; }
    }
}
